version: 2

before:
  hooks:
    # Generate manpage, completions and download owners CSV
    # download-owners must be the last executed target if not dummy CSV will be embedded instead.
    - make man-pages completions download-owners

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goarm:
      - '6'
      - '7'
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: darwin
        goarch: arm

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- if eq .Os "darwin" }}Darwin
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md
      - docs/*.md
      - man-pages/*
      - completions/*

# Goreleaser example:
# https://github.com/goreleaser/goreleaser/tree/main/.goreleaser.yaml
# https://github.com/goreleaser/goreleaser/tree/main/scripts
# https://github.com/goreleaser/goreleaser/blob/main/cmd/man.go
homebrew_casks:
  - repository:
      owner: mrclmr
      name: homebrew-tap
    directory: Casks
    description: "Generate or validate intermodal container markings."
    homepage: "https://github.com/mrclmr/icm"
    manpages:
      # This list is unfortunately manually maintained.
      - 'man-pages/icm.1'
      - 'man-pages/icm-download-owners.1'
      - 'man-pages/icm-generate.1'
      - 'man-pages/icm-validate.1'
    completions:
      bash: 'completions/icm.bash'
      zsh: 'completions/icm.zsh'
      fish: 'completions/icm.fish'
    hooks:
      post:
        install: |
          system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/icm"]

scoops:
  - repository:
      owner: mrclmr
      name: scoop-bucket
    description: "Generate or validate intermodal container markings."
    homepage: "https://github.com/mrclmr/icm"
    license: 'MIT'
